import bpy
from dataclasses import dataclass

@dataclass
class ParsedNode:
    inputs: dict
    nodes: dict
    links: list
    
    def generate_group(self, name):
        '''
        Current limitations:
            Don't use multiple links from group input node (use reroute).
            Group output has one output.
        '''
#        sort links
        sorted_names = [i['name'] for i in self.inputs]
        sorted_gil = [l for name in sorted_names for l in self.links if l[0][0]=='Group Input' and l[0][1]==name]
        other_gil = [l for l in self.links if not l[0][0]=='Group Input']
        sorted_links = sorted_gil + other_gil
        
        new_group = bpy.data.node_groups.new(name, 'ShaderNodeTree')
        nodes = new_group.nodes
        links = new_group.links
#        inp = nodes.new("NodeGroupInput")
#        out = nodes.new("NodeGroupOutput")
        
        for node_dict in self.nodes:
            bl_idname = node_dict.pop('bl_idname')
            parent = node_dict.pop('parent')
            node = nodes.new(bl_idname)
            node['parent'] = parent
            if parent:
                node['location'] = node_dict.pop('location')
            for key, val in node_dict.items():
                setattr(node, key, val)
            if bl_idname == 'NodeGroupInput':
                for input_dict in self.inputs:
                    soc = new_group.inputs.new(input_dict['bl_idname'], input_dict['name'])
            elif bl_idname == 'NodeGroupOutput':
                soc = new_group.outputs.new('NodeSocketShader', 'Shader')
        
#        set frames
        for node in nodes:
            if node['parent']:
                node.parent = nodes[node['parent']]
                node.location = node['location']
        
        for link in self.links:
            from_comp, to_comp = link
            print(from_comp, to_comp)
            from_soc = nodes[from_comp[0]].outputs[from_comp[1]]
            to_soc = nodes[to_comp[0]].inputs[to_comp[1]]
            links.new(from_soc, to_soc)
            
        

def nodes2dict():
    active_node_group = bpy.context.object.active_material.node_tree.nodes.active
    def _str(prop, val):
        # print list-like objects as lists
        if isinstance(val, bpy.types.Node):
            return val.name
        if hasattr(val, '__getitem__'):
            print(prop, prop.identifier, val)
            return val[:]
        return val
    inputs = []
    for input in active_node_group.inputs:
        inputs.append( {prop.identifier: _str(prop, getattr(input, prop.identifier)) for prop in input.rna_type.properties if not prop.is_readonly and prop.type in {'STRING', 'INT', 'BOOLEAN', 'FLOAT', 'ENUM'}} )
        
    nodes = []
    for node in active_node_group.node_tree.nodes:
        nodes.append( {prop.identifier: _str(prop, getattr(node, prop.identifier)) for prop in node.rna_type.properties if not prop.is_readonly and prop.type in {'STRING', 'INT', 'BOOLEAN', 'FLOAT', 'POINTER'} and prop.identifier not in {'node_tree'}} )
    
    links = []
    for link in active_node_group.node_tree.links:
        links.append( ((link.from_node.name, link.from_socket.name), (link.to_node.name, link.to_socket.name)) )
    
    parsed = ParsedNode(inputs, nodes, links)
#    print(parsed)
    return parsed

group = ParsedNode(inputs=[{'bl_idname': 'NodeSocketFloatFactor',
                    'bl_label': 'Float',
                    'default_value': 0.0,
                    'description': '',
                    'display_shape': 'CIRCLE',
                    'enabled': True,
                    'hide': False,
                    'hide_value': False,
                    'link_limit': 1,
                    'name': 'Diffuse_bool',
                    'show_expanded': False,
                    'type': 'VALUE'},
                   {'bl_idname': 'NodeSocketFloatFactor',
                    'bl_label': 'Float',
                    'default_value': 1.0,
                    'description': '',
                    'display_shape': 'CIRCLE',
                    'enabled': True,
                    'hide': False,
                    'hide_value': False,
                    'link_limit': 1,
                    'name': 'Phong_bool',
                    'show_expanded': False,
                    'type': 'VALUE'},
                   {'bl_idname': 'NodeSocketColor',
                    'bl_label': 'Color',
                    'default_value': (0.06327445805072784,
                                      0.8000000715255737,
                                      0.0,
                                      1.0),
                    'description': '',
                    'display_shape': 'CIRCLE',
                    'enabled': True,
                    'hide': False,
                    'hide_value': False,
                    'link_limit': 1,
                    'name': 'Diffuse_Color',
                    'show_expanded': False,
                    'type': 'RGBA'},
                   {'bl_idname': 'NodeSocketFloatFactor',
                    'bl_label': 'Float',
                    'default_value': 0.0,
                    'description': '',
                    'display_shape': 'CIRCLE',
                    'enabled': True,
                    'hide': False,
                    'hide_value': False,
                    'link_limit': 1,
                    'name': 'S Emission_bool',
                    'show_expanded': False,
                    'type': 'VALUE'},
                   {'bl_idname': 'NodeSocketColor',
                    'bl_label': 'Color',
                    'default_value': (0.6718317270278931, 0.0, 1.0, 1.0),
                    'description': '',
                    'display_shape': 'CIRCLE',
                    'enabled': True,
                    'hide': False,
                    'hide_value': False,
                    'link_limit': 1,
                    'name': 'S Emission Color',
                    'show_expanded': False,
                    'type': 'RGBA'},
                   {'bl_idname': 'NodeSocketFloat',
                    'bl_label': 'Float',
                    'default_value': 1.0,
                    'description': '',
                    'display_shape': 'CIRCLE',
                    'enabled': True,
                    'hide': False,
                    'hide_value': False,
                    'link_limit': 1,
                    'name': 'S Emission Strength',
                    'show_expanded': False,
                    'type': 'VALUE'}],
           nodes=[{'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'NodeFrame',
                   'bl_label': 'Frame',
                   'bl_width_default': 150.0,
                   'bl_width_max': 3.4028234663852886e+38,
                   'bl_width_min': 100.0,
                   'color': (0.6079999804496765,
                             0.6079999804496765,
                             0.6079999804496765),
                   'height': 211.0,
                   'hide': False,
                   'label': 'Phong',
                   'label_size': 20,
                   'location': (-96.45079040527344, -316.8763427734375),
                   'mute': False,
                   'name': 'Frame.003',
                   'parent': None,
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'shrink': True,
                   'text': None,
                   'use_custom_color': False,
                   'width': 670.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'NodeFrame',
                   'bl_label': 'Frame',
                   'bl_width_default': 150.0,
                   'bl_width_max': 3.4028234663852886e+38,
                   'bl_width_min': 100.0,
                   'color': (0.6079999804496765,
                             0.6079999804496765,
                             0.6079999804496765),
                   'height': 238.0,
                   'hide': False,
                   'label': 'Diffuse',
                   'label_size': 20,
                   'location': (-154.00216674804688, -24.173065185546875),
                   'mute': False,
                   'name': 'Frame.002',
                   'parent': None,
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'shrink': True,
                   'text': None,
                   'use_custom_color': False,
                   'width': 679.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'NodeFrame',
                   'bl_label': 'Frame',
                   'bl_width_default': 150.0,
                   'bl_width_max': 3.4028234663852886e+38,
                   'bl_width_min': 100.0,
                   'color': (0.2265842854976654, 0.006075043696910143, 0.0),
                   'height': 393.0,
                   'hide': False,
                   'label': 'Select Material Type',
                   'label_size': 20,
                   'location': (-7.791164398193359, -767.5952758789062),
                   'mute': False,
                   'name': 'Frame.001',
                   'parent': None,
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'shrink': True,
                   'text': None,
                   'use_custom_color': True,
                   'width': 207.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'NodeFrame',
                   'bl_label': 'Frame',
                   'bl_width_default': 150.0,
                   'bl_width_max': 3.4028234663852886e+38,
                   'bl_width_min': 100.0,
                   'color': (0.23301564157009125,
                             0.23301564157009125,
                             0.23301564157009125),
                   'height': 335.0,
                   'hide': False,
                   'label': 'Emission',
                   'label_size': 20,
                   'location': (-2571.856201171875, -629.9427490234375),
                   'mute': False,
                   'name': 'Frame',
                   'parent': None,
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'shrink': True,
                   'text': None,
                   'use_custom_color': True,
                   'width': 825.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'NodeReroute',
                   'bl_label': 'Reroute',
                   'bl_width_default': 140.0,
                   'bl_width_max': 700.0,
                   'bl_width_min': 100.0,
                   'color': (0.6079999804496765,
                             0.6079999804496765,
                             0.6079999804496765),
                   'height': 100.0,
                   'hide': False,
                   'label': '',
                   'location': (530.8294067382812, 227.0684814453125),
                   'mute': False,
                   'name': 'Reroute.001',
                   'parent': None,
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'use_custom_color': False,
                   'width': 16.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'NodeReroute',
                   'bl_label': 'Reroute',
                   'bl_width_default': 140.0,
                   'bl_width_max': 700.0,
                   'bl_width_min': 100.0,
                   'color': (0.6079999804496765,
                             0.6079999804496765,
                             0.6079999804496765),
                   'height': 100.0,
                   'hide': False,
                   'label': '',
                   'location': (-643.17041015625, 223.58326721191406),
                   'mute': False,
                   'name': 'Reroute.002',
                   'parent': None,
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'use_custom_color': False,
                   'width': 16.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'NodeReroute',
                   'bl_label': 'Reroute',
                   'bl_width_default': 140.0,
                   'bl_width_max': 700.0,
                   'bl_width_min': 100.0,
                   'color': (0.6079999804496765,
                             0.6079999804496765,
                             0.6079999804496765),
                   'height': 100.0,
                   'hide': False,
                   'label': '',
                   'location': (524.0386352539062, 200.1834716796875),
                   'mute': False,
                   'name': 'Reroute.003',
                   'parent': None,
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'use_custom_color': False,
                   'width': 16.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'NodeReroute',
                   'bl_label': 'Reroute',
                   'bl_width_default': 140.0,
                   'bl_width_max': 700.0,
                   'bl_width_min': 100.0,
                   'color': (0.6079999804496765,
                             0.6079999804496765,
                             0.6079999804496765),
                   'height': 100.0,
                   'hide': False,
                   'label': '',
                   'location': (-643.0267944335938, 198.5223388671875),
                   'mute': False,
                   'name': 'Reroute',
                   'parent': None,
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'use_custom_color': False,
                   'width': 16.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'ShaderNodeAddShader',
                   'bl_label': 'Add Shader',
                   'bl_width_default': 140.0,
                   'bl_width_max': 700.0,
                   'bl_width_min': 100.0,
                   'color': (0.6079999804496765,
                             0.6079999804496765,
                             0.6079999804496765),
                   'height': 100.0,
                   'hide': False,
                   'label': '',
                   'location': (945.7998657226562, -8.742431640625),
                   'mute': False,
                   'name': 'Add Shader.001',
                   'parent': None,
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'use_custom_color': False,
                   'width': 140.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'NodeGroupOutput',
                   'bl_label': 'Group Output',
                   'bl_width_default': 140.0,
                   'bl_width_max': 400.0,
                   'bl_width_min': 80.0,
                   'color': (0.6079999804496765,
                             0.6079999804496765,
                             0.6079999804496765),
                   'height': 100.0,
                   'hide': False,
                   'is_active_output': True,
                   'label': '',
                   'location': (1192.3515625, -62.69669723510742),
                   'mute': False,
                   'name': 'Group Output',
                   'parent': None,
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'use_custom_color': False,
                   'width': 140.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'ShaderNodeBsdfGlossy',
                   'bl_label': 'Glossy BSDF',
                   'bl_width_default': 150.0,
                   'bl_width_max': 700.0,
                   'bl_width_min': 120.0,
                   'color': (0.6079999804496765,
                             0.6079999804496765,
                             0.6079999804496765),
                   'height': 100.0,
                   'hide': False,
                   'label': '',
                   'location': (-228.7256317138672, 112.45697021484375),
                   'mute': False,
                   'name': 'Glossy BSDF',
                   'parent': 'Frame.003',
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'use_custom_color': False,
                   'width': 150.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'ShaderNodeAddShader',
                   'bl_label': 'Add Shader',
                   'bl_width_default': 140.0,
                   'bl_width_max': 700.0,
                   'bl_width_min': 100.0,
                   'color': (0.6079999804496765,
                             0.6079999804496765,
                             0.6079999804496765),
                   'height': 100.0,
                   'hide': False,
                   'label': '',
                   'location': (241.59181213378906, 67.115966796875),
                   'mute': False,
                   'name': 'Add Shader.002',
                   'parent': 'Frame.003',
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'use_custom_color': False,
                   'width': 140.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'ShaderNodeAddShader',
                   'bl_label': 'Add Shader',
                   'bl_width_default': 140.0,
                   'bl_width_max': 700.0,
                   'bl_width_min': 100.0,
                   'color': (0.6079999804496765,
                             0.6079999804496765,
                             0.6079999804496765),
                   'height': 100.0,
                   'hide': False,
                   'label': '',
                   'location': (295.8738708496094, 76.3155517578125),
                   'mute': False,
                   'name': 'Add Shader',
                   'parent': 'Frame.002',
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'use_custom_color': False,
                   'width': 140.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'ShaderNodeBsdfDiffuse',
                   'bl_label': 'Diffuse BSDF',
                   'bl_width_default': 150.0,
                   'bl_width_max': 700.0,
                   'bl_width_min': 120.0,
                   'color': (0.6079999804496765,
                             0.6079999804496765,
                             0.6079999804496765),
                   'height': 100.0,
                   'hide': False,
                   'label': '',
                   'location': (-182.9437255859375, 156.74270629882812),
                   'mute': False,
                   'name': 'Diffuse BSDF',
                   'parent': 'Frame.002',
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'use_custom_color': False,
                   'width': 150.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'ShaderNodeMixShader',
                   'bl_label': 'Mix Shader',
                   'bl_width_default': 140.0,
                   'bl_width_max': 700.0,
                   'bl_width_min': 100.0,
                   'color': (0.6079999804496765,
                             0.6079999804496765,
                             0.6079999804496765),
                   'height': 100.0,
                   'hide': False,
                   'label': 'Phong',
                   'location': (682.150390625, 571.0927734375),
                   'mute': False,
                   'name': 'Mix Shader.002',
                   'parent': 'Frame.001',
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'use_custom_color': False,
                   'width': 140.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'ShaderNodeMixShader',
                   'bl_label': 'Mix Shader',
                   'bl_width_default': 140.0,
                   'bl_width_max': 700.0,
                   'bl_width_min': 100.0,
                   'color': (0.6079999804496765,
                             0.6079999804496765,
                             0.6079999804496765),
                   'height': 100.0,
                   'hide': False,
                   'label': 'Diffuse',
                   'location': (688.8963012695312, 784.5928955078125),
                   'mute': False,
                   'name': 'Mix Shader.003',
                   'parent': 'Frame.001',
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'use_custom_color': False,
                   'width': 140.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'ShaderNodeMixShader',
                   'bl_label': 'Mix Shader',
                   'bl_width_default': 140.0,
                   'bl_width_max': 700.0,
                   'bl_width_min': 100.0,
                   'color': (0.6079999804496765,
                             0.6079999804496765,
                             0.6079999804496765),
                   'height': 100.0,
                   'hide': False,
                   'label': '',
                   'location': (1660.22802734375, 361.6156005859375),
                   'mute': False,
                   'name': 'Mix Shader.001',
                   'parent': 'Frame',
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'use_custom_color': False,
                   'width': 140.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'ShaderNodeNewGeometry',
                   'bl_label': 'Geometry',
                   'bl_width_default': 140.0,
                   'bl_width_max': 700.0,
                   'bl_width_min': 100.0,
                   'color': (0.6079999804496765,
                             0.6079999804496765,
                             0.6079999804496765),
                   'height': 100.0,
                   'hide': False,
                   'label': '',
                   'location': (1444.6348876953125, 357.0958557128906),
                   'mute': False,
                   'name': 'Geometry',
                   'parent': 'Frame',
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'use_custom_color': False,
                   'width': 140.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'ShaderNodeMixShader',
                   'bl_label': 'Mix Shader',
                   'bl_width_default': 140.0,
                   'bl_width_max': 700.0,
                   'bl_width_min': 100.0,
                   'color': (0.6079999804496765,
                             0.6079999804496765,
                             0.6079999804496765),
                   'height': 100.0,
                   'hide': False,
                   'label': '',
                   'location': (1880.0, 405.5359191894531),
                   'mute': False,
                   'name': 'Mix Shader',
                   'parent': 'Frame',
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'use_custom_color': False,
                   'width': 140.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'ShaderNodeEmission',
                   'bl_label': 'Emission',
                   'bl_width_default': 140.0,
                   'bl_width_max': 700.0,
                   'bl_width_min': 100.0,
                   'color': (0.6079999804496765,
                             0.6079999804496765,
                             0.6079999804496765),
                   'height': 100.0,
                   'hide': False,
                   'label': '',
                   'location': (1254.491943359375, 298.28485107421875),
                   'mute': False,
                   'name': 'Emission',
                   'parent': 'Frame',
                   'select': False,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'use_custom_color': False,
                   'width': 140.0,
                   'width_hidden': 42.0},
                  {'bl_description': '',
                   'bl_height_default': 100.0,
                   'bl_height_max': 30.0,
                   'bl_height_min': 30.0,
                   'bl_idname': 'NodeGroupInput',
                   'bl_label': 'Group Input',
                   'bl_width_default': 140.0,
                   'bl_width_max': 400.0,
                   'bl_width_min': 80.0,
                   'color': (0.6079999804496765,
                             0.6079999804496765,
                             0.6079999804496765),
                   'height': 100.0,
                   'hide': False,
                   'label': '',
                   'location': (-1803.0408935546875, -161.83985900878906),
                   'mute': False,
                   'name': 'Group Input',
                   'parent': None,
                   'select': True,
                   'show_options': True,
                   'show_preview': False,
                   'show_texture': False,
                   'use_custom_color': False,
                   'width': 140.0,
                   'width_hidden': 42.0}],
           links=[(('Mix Shader', 'Shader'), ('Add Shader', 'Shader')),
                  (('Geometry', 'Backfacing'), ('Mix Shader.001', 'Fac')),
                  (('Emission', 'Emission'), ('Mix Shader.001', 'Shader')),
                  (('Diffuse BSDF', 'BSDF'), ('Add Shader', 'Shader')),
                  (('Mix Shader.001', 'Shader'), ('Mix Shader', 'Shader')),
                  (('Group Input', 'Diffuse_Color'), ('Diffuse BSDF', 'Color')),
                  (('Group Input', 'S Emission Color'), ('Emission', 'Color')),
                  (('Group Input', 'S Emission_bool'), ('Mix Shader', 'Fac')),
                  (('Group Input', 'S Emission Strength'),
                   ('Emission', 'Strength')),
                  (('Mix Shader.002', 'Shader'), ('Add Shader.001', 'Shader')),
                  (('Add Shader.002', 'Shader'), ('Mix Shader.002', 'Shader')),
                  (('Add Shader', 'Shader'), ('Mix Shader.003', 'Shader')),
                  (('Reroute.001', 'Output'), ('Mix Shader.003', 'Fac')),
                  (('Reroute.003', 'Output'), ('Mix Shader.002', 'Fac')),
                  (('Mix Shader.003', 'Shader'), ('Add Shader.001', 'Shader')),
                  (('Group Input', 'Phong_bool'), ('Reroute', 'Input')),
                  (('Reroute.002', 'Output'), ('Reroute.001', 'Input')),
                  (('Group Input', 'Diffuse_bool'), ('Reroute.002', 'Input')),
                  (('Glossy BSDF', 'BSDF'), ('Add Shader.002', 'Shader')),
                  (('Mix Shader', 'Shader'), ('Add Shader.002', 'Shader')),
                  (('Add Shader.001', 'Shader'), ('Group Output', 'Shader')),
                  (('Reroute', 'Output'), ('Reroute.003', 'Input'))])

if __name__ == "__main__":
#    generate dict from selected node group
#    p=nodes2dict()
#    import pprint
#    pprint.pprint(p)

#    use dict to create node group
    group.generate_group('IndigoUberShader')
